version: '1.0' #NE PAS MODIFIER
maincommand:
  permission: grade.use #Permission pour la commande /grade
  permission_message: '§cCe serveur ne t''autorise pas à éxécuter cette commande.' #Message renvoyé si le joueur n'as pas la permission.
  prefix: '&7[&bGrades&b&lSk&r&7]&3 »&6' #Prefix du plugin.
commandliste:
  permission: grade.seeliste #Permission pour la commande /list (liste les grades/joueurs d'un grade
  permission_message: '§cCe serveur ne t''autorise pas à éxécuter cette commande.' #Message renvoyé si le joueur n'as pas la permission.
grades:
  playerlist: true #Mets le préfix du joueur dans le tab <true/false>
  chat: true #Mets le préfix du joueur dans le chat <true/false>
  player_name: false #Nécéssite NTE. si activé, Permet de mettre le grade du joueur au dessus de sa tête <true/false> [~ SOON]
  default_prefix: '&e[Nouveau]' #Préfix par défaut quand un nouveau joueur rejoint le serveur, nécéssite SkRayFall.
plugin:
  versions: 'Skript2.2-dev34, skript-yaml 1.1.5, SkRayFall 1.9.10 et SkUtilites 0.9.0' #Versions des addons nécessaire, Confirmé sans bugs. NE PAS MODIFIER
  Use_NTE: false #Ajout de la comptabilité avec NameTagEdit. Sert à mettre le grade du joueur au dessus de sa tête. <true/false> [~ SOON]
  name_NTE: NameTagEdit.jar #Nom du plugins NTE. [~ SOON]
